DROP TABLE IF EXISTS `h_core_tx_union_his_perf_test`;
CREATE TABLE `h_core_tx_union_his_perf_test`
(
    `acctt`        varchar(64) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '账号',
    `acct`         varchar(64) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '款项代码',
    `acctt1`       varchar(80) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '旧账号',
    `crdno`        varchar(38) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '卡号',
    `supflg`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '主附卡标志',
    `trnorg`       varchar(18) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '机构代码',
    `name`         varchar(180) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '户名',
    `trndate`      varchar(40) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '发生日期',
    `subno`        varchar(24) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '科目号',
    `atuntt`       varchar(27) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '归属机构',
    `opnorg`       varchar(27) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '开户机构',
    `ccy`          varchar(9) COLLATE utf8mb4_bin    DEFAULT NULL COMMENT '币种',
    `amt`          decimal(34, 2)                    DEFAULT NULL COMMENT '发生额',
    `dcflg`        varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '借贷标志 d借c贷',
    `dcflg_d`      decimal(34, 2)                    DEFAULT NULL COMMENT '借方发生额',
    `dcflg_c`      decimal(34, 2)                    DEFAULT NULL COMMENT '贷方发生额',
    `bal`          decimal(34, 2)                    DEFAULT NULL COMMENT '余额',
    `ctflg`        varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '现转标识 1现金2转账',
    `ctflg_name`   varchar(36) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '现转标识名称',
    `otnm1`        varchar(180) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '对方行名(对方银行名称)',
    `opp_organkey` varchar(60) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '对方行号',
    `oacctt`       varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '对方账号',
    `oacct`        varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '对方款项',
    `vounum1`      decimal(20, 0)                    DEFAULT NULL COMMENT '客户支票号',
    `vounum2`      decimal(20, 0)                    DEFAULT NULL COMMENT '凭证账号',
    `voupre`       varchar(30) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '冠字码',
    `voucls`       varchar(9) COLLATE utf8mb4_bin    DEFAULT NULL COMMENT '凭证类型',
    `syts`         varchar(24) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '交易时间_时分秒',
    `crts`         varchar(200) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '交易时间_时间戳',
    `otbkac`       varchar(2000) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '他行账号(对方账号)',
    `otacnm`       varchar(180) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '他行户名(交易对手名称)',
    `chnlcod`      varchar(24) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '交易渠道',
    `chnlcod_name` varchar(100) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '交易渠道名称',
    `rmks`         varchar(200) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '摘要',
    `teller`       varchar(30) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '经办柜员',
    `ptxseq`       int(11)                           DEFAULT NULL COMMENT '原交易流水号',
    `ctxseq`       int(11)                           DEFAULT NULL COMMENT '子交易流水号',
    `seq`          int(11)                           DEFAULT NULL COMMENT '顺序号',
    `dodflg`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '定活标志 0:活 1:定',
    `cshexc`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '钞汇鉴别',
    `cshatr`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '钞汇属性',
    `cbcdir`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '余额方向 c:活 空:定',
    `code`         varchar(64) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '核心交易码',
    `amtflg`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '交易额红蓝字标志0:蓝 1:红',
    `balflg`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '余额红蓝字标志0:蓝 1:红',
    `trnamt`       decimal(34, 2)                    DEFAULT NULL COMMENT '交易金额',
    `accbal`       decimal(34, 2)                    DEFAULT NULL COMMENT '交易后余额',
    `rmkcde`       varchar(20) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '摘要码',
    `summry`       varchar(120) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '摘要',
    `orgnam`       varchar(180) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '交易网点名称',
    `orgsn`        varchar(180) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '交易网点简称',
    `usrdef`       varchar(180) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '自定义域',
    `tdds`         varchar(300) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '交易说明',
    `tdtonm`       varchar(180) COLLATE utf8mb4_bin  DEFAULT NULL COMMENT '交易对手名称',
    `rcdtyp`       varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '记录类型',
    `incr_mark`    varchar(30) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '更新标志',
    `flag`         varchar(10) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '数据来源标志',
    `flagdes`      varchar(20) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '数据来源标志描述',
    `etl_dt`       varchar(20) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '历史数据平台跑批日期',
    `partition_dt` varchar(20) COLLATE utf8mb4_bin   DEFAULT NULL COMMENT '分区字段',
    KEY `idx_h_core_tx_union_his_perf_test_1` (`acctt`, `partition_dt`, `trndate`)
) ENGINE = SEQUOIADB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin
  ROW_FORMAT = DYNAMIC COMMENT ='sequoiadb:{table_options:{Compressed:true,CompressionType:''lzw''}}';